services:
  certbot-init:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    image: ${IMAGE_NAME}-certbot
    container_name: ${CONTAINER_NAME}-certbot-init
    env_file:
      - gateway.env
    environment:
      CERTBOT_MODE: init
    network_mode: host
    volumes:
      - "${BASE_DIR}/letsencrypt:/etc/letsencrypt:z"
      - "${BASE_DIR}/letsencrypt-lib:/var/lib/letsencrypt:z"

  certbot-renew:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    image: ${IMAGE_NAME}-certbot
    container_name: ${CONTAINER_NAME}-certbot-renew
    env_file:
      - gateway.env
    environment:
      CERTBOT_MODE: renew
    restart: unless-stopped
    depends_on:
      certbot-init:
        condition: service_completed_successfully
    network_mode: host
    volumes:
      - "${BASE_DIR}/letsencrypt:/etc/letsencrypt:z"
      - "${BASE_DIR}/letsencrypt-lib:/var/lib/letsencrypt:z"

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    env_file:
      - gateway.env
    restart: unless-stopped
    depends_on:
      certbot-init:
        condition: service_completed_successfully
    network_mode: host
    volumes:
      - "${BASE_DIR}/letsencrypt:/etc/letsencrypt:ro,z"
      - "${BASE_DIR}/data:/mosquitto/data:z"
      - "${BASE_DIR}/pki:/broker-pki:ro,z"

  admin-web:
    build:
      context: ./admin-web
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}-admin-web
    container_name: ${CONTAINER_NAME}-admin-web
    env_file:
      - gateway.env
    restart: unless-stopped
    depends_on:
      broker:
        condition: service_started
    network_mode: host
    volumes:
      - "${BASE_DIR}/admin-web:/data:z"
      - "${BASE_DIR}/letsencrypt:/etc/letsencrypt:ro,z"
      - "${BASE_DIR}/pki:/broker-pki:ro,z"

  admin-nginx:
    build:
      context: ./admin-nginx
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}-admin-nginx
    container_name: ${CONTAINER_NAME}-admin-nginx
    env_file:
      - gateway.env
    restart: unless-stopped
    depends_on:
      admin-web:
        condition: service_started
      certbot-init:
        condition: service_completed_successfully
    network_mode: host
    volumes:
      - "${BASE_DIR}/letsencrypt:/etc/letsencrypt:ro,z"
